/*
 * This file is generated by jOOQ.
 */
package com.example.db;


import com.example.db.tables.Auth;
import com.example.db.tables.Friendship;
import com.example.db.tables.Posts;
import com.example.db.tables.Sessions;
import com.example.db.tables.Settings;
import com.example.db.tables.Users;
import com.example.db.tables.Verification;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in Java
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>Java.Auth</code>.
     */
    public static final Auth AUTH = Auth.AUTH;

    /**
     * The table <code>Java.Friendship</code>.
     */
    public static final Friendship FRIENDSHIP = Friendship.FRIENDSHIP;

    /**
     * The table <code>Java.Posts</code>.
     */
    public static final Posts POSTS = Posts.POSTS;

    /**
     * The table <code>Java.Sessions</code>.
     */
    public static final Sessions SESSIONS = Sessions.SESSIONS;

    /**
     * The table <code>Java.Settings</code>.
     */
    public static final Settings SETTINGS = Settings.SETTINGS;

    /**
     * The table <code>Java.Users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>Java.Verification</code>.
     */
    public static final Verification VERIFICATION = Verification.VERIFICATION;
}
