/*
 * This file is generated by jOOQ.
 */
package com.example.db.routines;


import com.example.db.Java;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthWithEmail extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 2099186236;

    /**
     * The parameter <code>Java.Auth_With_Email.inEmail</code>.
     */
    public static final Parameter<String> INEMAIL = Internal.createParameter("inEmail", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * The parameter <code>Java.Auth_With_Email.outVal</code>.
     */
    public static final Parameter<String> OUTVAL = Internal.createParameter("outVal", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * Create a new routine call instance
     */
    public AuthWithEmail() {
        super("Auth_With_Email", Java.JAVA);

        addInParameter(INEMAIL);
        addOutParameter(OUTVAL);
    }

    /**
     * Set the <code>inEmail</code> parameter IN value to the routine
     */
    public void setInemail(String value) {
        setValue(INEMAIL, value);
    }

    /**
     * Get the <code>outVal</code> parameter OUT value from the routine
     */
    public String getOutval() {
        return get(OUTVAL);
    }
}
