/*
 * This file is generated by jOOQ.
 */
package com.example.db.routines;


import com.example.db.Java;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeleteUserByEmail extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -1186244467;

    /**
     * The parameter <code>Java.Delete_User_By_Email.userEmail</code>.
     */
    public static final Parameter<String> USEREMAIL = Internal.createParameter("userEmail", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * Create a new routine call instance
     */
    public DeleteUserByEmail() {
        super("Delete_User_By_Email", Java.JAVA);

        addInParameter(USEREMAIL);
    }

    /**
     * Set the <code>userEmail</code> parameter IN value to the routine
     */
    public void setUseremail(String value) {
        setValue(USEREMAIL, value);
    }
}
