/*
 * This file is generated by jOOQ.
 */
package com.example.db.routines;


import com.example.db.Java;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PublishPost extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 379836288;

    /**
     * The parameter <code>Java.Publish_Post.inText</code>.
     */
    public static final Parameter<String> INTEXT = Internal.createParameter("inText", org.jooq.impl.SQLDataType.VARCHAR(2048), false, false);

    /**
     * The parameter <code>Java.Publish_Post.inUser</code>.
     */
    public static final Parameter<Integer> INUSER = Internal.createParameter("inUser", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public PublishPost() {
        super("Publish_Post", Java.JAVA);

        addInParameter(INTEXT);
        addInParameter(INUSER);
    }

    /**
     * Set the <code>inText</code> parameter IN value to the routine
     */
    public void setIntext(String value) {
        setValue(INTEXT, value);
    }

    /**
     * Set the <code>inUser</code> parameter IN value to the routine
     */
    public void setInuser(Integer value) {
        setValue(INUSER, value);
    }
}
