/*
 * This file is generated by jOOQ.
 */
package com.astroapi.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import com.astroapi.db.tables.Settings;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SettingsRecord extends UpdatableRecordImpl<SettingsRecord> implements Record4<Integer, Integer, Byte, String> {

    private static final long serialVersionUID = -2106281984;

    /**
     * Setter for <code>Java.Settings.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Java.Settings.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Java.Settings.userId</code>.
     */
    public void setUserid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>Java.Settings.userId</code>.
     */
    public Integer getUserid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>Java.Settings.show_own_posts_in_feed</code>.
     */
    public void setShowOwnPostsInFeed(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>Java.Settings.show_own_posts_in_feed</code>.
     */
    public Byte getShowOwnPostsInFeed() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>Java.Settings.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>Java.Settings.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Byte, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, Byte, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Settings.SETTINGS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Settings.SETTINGS.USERID;
    }

    @Override
    public Field<Byte> field3() {
        return Settings.SETTINGS.SHOW_OWN_POSTS_IN_FEED;
    }

    @Override
    public Field<String> field4() {
        return Settings.SETTINGS.EMAIL;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getUserid();
    }

    @Override
    public Byte component3() {
        return getShowOwnPostsInFeed();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getUserid();
    }

    @Override
    public Byte value3() {
        return getShowOwnPostsInFeed();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public SettingsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SettingsRecord value2(Integer value) {
        setUserid(value);
        return this;
    }

    @Override
    public SettingsRecord value3(Byte value) {
        setShowOwnPostsInFeed(value);
        return this;
    }

    @Override
    public SettingsRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public SettingsRecord values(Integer value1, Integer value2, Byte value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SettingsRecord
     */
    public SettingsRecord() {
        super(Settings.SETTINGS);
    }

    /**
     * Create a detached, initialised SettingsRecord
     */
    public SettingsRecord(Integer id, Integer userid, Byte showOwnPostsInFeed, String email) {
        super(Settings.SETTINGS);

        set(0, id);
        set(1, userid);
        set(2, showOwnPostsInFeed);
        set(3, email);
    }
}
