/*
 * This file is generated by jOOQ.
 */
package com.astroapi.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import com.astroapi.db.tables.Verification;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VerificationRecord extends UpdatableRecordImpl<VerificationRecord> implements Record4<Integer, String, String, String> {

    private static final long serialVersionUID = 826613388;

    /**
     * Setter for <code>Java.Verification.VerificationID</code>.
     */
    public void setVerificationid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Java.Verification.VerificationID</code>.
     */
    public Integer getVerificationid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Java.Verification.UserEmail</code>.
     */
    public void setUseremail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Java.Verification.UserEmail</code>.
     */
    public String getUseremail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Java.Verification.VerificationExpiry</code>.
     */
    public void setVerificationexpiry(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>Java.Verification.VerificationExpiry</code>.
     */
    public String getVerificationexpiry() {
        return (String) get(2);
    }

    /**
     * Setter for <code>Java.Verification.VerificationCode</code>.
     */
    public void setVerificationcode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>Java.Verification.VerificationCode</code>.
     */
    public String getVerificationcode() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Verification.VERIFICATION.VERIFICATIONID;
    }

    @Override
    public Field<String> field2() {
        return Verification.VERIFICATION.USEREMAIL;
    }

    @Override
    public Field<String> field3() {
        return Verification.VERIFICATION.VERIFICATIONEXPIRY;
    }

    @Override
    public Field<String> field4() {
        return Verification.VERIFICATION.VERIFICATIONCODE;
    }

    @Override
    public Integer component1() {
        return getVerificationid();
    }

    @Override
    public String component2() {
        return getUseremail();
    }

    @Override
    public String component3() {
        return getVerificationexpiry();
    }

    @Override
    public String component4() {
        return getVerificationcode();
    }

    @Override
    public Integer value1() {
        return getVerificationid();
    }

    @Override
    public String value2() {
        return getUseremail();
    }

    @Override
    public String value3() {
        return getVerificationexpiry();
    }

    @Override
    public String value4() {
        return getVerificationcode();
    }

    @Override
    public VerificationRecord value1(Integer value) {
        setVerificationid(value);
        return this;
    }

    @Override
    public VerificationRecord value2(String value) {
        setUseremail(value);
        return this;
    }

    @Override
    public VerificationRecord value3(String value) {
        setVerificationexpiry(value);
        return this;
    }

    @Override
    public VerificationRecord value4(String value) {
        setVerificationcode(value);
        return this;
    }

    @Override
    public VerificationRecord values(Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VerificationRecord
     */
    public VerificationRecord() {
        super(Verification.VERIFICATION);
    }

    /**
     * Create a detached, initialised VerificationRecord
     */
    public VerificationRecord(Integer verificationid, String useremail, String verificationexpiry, String verificationcode) {
        super(Verification.VERIFICATION);

        set(0, verificationid);
        set(1, useremail);
        set(2, verificationexpiry);
        set(3, verificationcode);
    }
}
