/*
 * This file is generated by jOOQ.
 */
package com.astroapi.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import com.astroapi.db.Indexes;
import com.astroapi.db.Java;
import com.astroapi.db.Keys;
import com.astroapi.db.tables.records.SessionsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sessions extends TableImpl<SessionsRecord> {

    private static final long serialVersionUID = -236489273;

    /**
     * The reference instance of <code>Java.Sessions</code>
     */
    public static final Sessions SESSIONS = new Sessions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SessionsRecord> getRecordType() {
        return SessionsRecord.class;
    }

    /**
     * The column <code>Java.Sessions.session_id</code>.
     */
    public final TableField<SessionsRecord, Integer> SESSION_ID = createField(DSL.name("session_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>Java.Sessions.cookie</code>.
     */
    public final TableField<SessionsRecord, String> COOKIE = createField(DSL.name("cookie"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("n/a", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>Java.Sessions.user_id</code>.
     */
    public final TableField<SessionsRecord, Integer> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>Java.Sessions</code> table reference
     */
    public Sessions() {
        this(DSL.name("Sessions"), null);
    }

    /**
     * Create an aliased <code>Java.Sessions</code> table reference
     */
    public Sessions(String alias) {
        this(DSL.name(alias), SESSIONS);
    }

    /**
     * Create an aliased <code>Java.Sessions</code> table reference
     */
    public Sessions(Name alias) {
        this(alias, SESSIONS);
    }

    private Sessions(Name alias, Table<SessionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Sessions(Name alias, Table<SessionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Sessions(Table<O> child, ForeignKey<O, SessionsRecord> key) {
        super(child, key, SESSIONS);
    }

    @Override
    public Schema getSchema() {
        return Java.JAVA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SESSIONS_COOKIE_UNIQUE, Indexes.SESSIONS_PRIMARY, Indexes.SESSIONS_SESSION_ID_UNIQUE);
    }

    @Override
    public Identity<SessionsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SESSIONS;
    }

    @Override
    public UniqueKey<SessionsRecord> getPrimaryKey() {
        return Keys.KEY_SESSIONS_PRIMARY;
    }

    @Override
    public List<UniqueKey<SessionsRecord>> getKeys() {
        return Arrays.<UniqueKey<SessionsRecord>>asList(Keys.KEY_SESSIONS_PRIMARY, Keys.KEY_SESSIONS_SESSION_ID_UNIQUE, Keys.KEY_SESSIONS_COOKIE_UNIQUE);
    }

    @Override
    public Sessions as(String alias) {
        return new Sessions(DSL.name(alias), this);
    }

    @Override
    public Sessions as(Name alias) {
        return new Sessions(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Sessions rename(String name) {
        return new Sessions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sessions rename(Name name) {
        return new Sessions(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
