/*
 * This file is generated by jOOQ.
 */
package com.example.db.tables.records;


import com.example.db.tables.Posts;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostsRecord extends UpdatableRecordImpl<PostsRecord> implements Record6<Integer, Integer, String, Integer, Integer, Timestamp> {

    private static final long serialVersionUID = -1696180151;

    /**
     * Setter for <code>Java.Posts.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Java.Posts.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Java.Posts.userId</code>.
     */
    public void setUserid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>Java.Posts.userId</code>.
     */
    public Integer getUserid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>Java.Posts.body</code>.
     */
    public void setBody(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>Java.Posts.body</code>.
     */
    public String getBody() {
        return (String) get(2);
    }

    /**
     * Setter for <code>Java.Posts.likes</code>.
     */
    public void setLikes(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>Java.Posts.likes</code>.
     */
    public Integer getLikes() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>Java.Posts.comments</code>.
     */
    public void setComments(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>Java.Posts.comments</code>.
     */
    public Integer getComments() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>Java.Posts.date_posted</code>.
     */
    public void setDatePosted(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>Java.Posts.date_posted</code>.
     */
    public Timestamp getDatePosted() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, String, Integer, Integer, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, String, Integer, Integer, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Posts.POSTS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Posts.POSTS.USERID;
    }

    @Override
    public Field<String> field3() {
        return Posts.POSTS.BODY;
    }

    @Override
    public Field<Integer> field4() {
        return Posts.POSTS.LIKES;
    }

    @Override
    public Field<Integer> field5() {
        return Posts.POSTS.COMMENTS;
    }

    @Override
    public Field<Timestamp> field6() {
        return Posts.POSTS.DATE_POSTED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getUserid();
    }

    @Override
    public String component3() {
        return getBody();
    }

    @Override
    public Integer component4() {
        return getLikes();
    }

    @Override
    public Integer component5() {
        return getComments();
    }

    @Override
    public Timestamp component6() {
        return getDatePosted();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getUserid();
    }

    @Override
    public String value3() {
        return getBody();
    }

    @Override
    public Integer value4() {
        return getLikes();
    }

    @Override
    public Integer value5() {
        return getComments();
    }

    @Override
    public Timestamp value6() {
        return getDatePosted();
    }

    @Override
    public PostsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PostsRecord value2(Integer value) {
        setUserid(value);
        return this;
    }

    @Override
    public PostsRecord value3(String value) {
        setBody(value);
        return this;
    }

    @Override
    public PostsRecord value4(Integer value) {
        setLikes(value);
        return this;
    }

    @Override
    public PostsRecord value5(Integer value) {
        setComments(value);
        return this;
    }

    @Override
    public PostsRecord value6(Timestamp value) {
        setDatePosted(value);
        return this;
    }

    @Override
    public PostsRecord values(Integer value1, Integer value2, String value3, Integer value4, Integer value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PostsRecord
     */
    public PostsRecord() {
        super(Posts.POSTS);
    }

    /**
     * Create a detached, initialised PostsRecord
     */
    public PostsRecord(Integer id, Integer userid, String body, Integer likes, Integer comments, Timestamp datePosted) {
        super(Posts.POSTS);

        set(0, id);
        set(1, userid);
        set(2, body);
        set(3, likes);
        set(4, comments);
        set(5, datePosted);
    }
}
