/*
 * This file is generated by jOOQ.
 */
package com.example.db.tables.records;


import com.example.db.tables.Sessions;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionsRecord extends UpdatableRecordImpl<SessionsRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = -28833020;

    /**
     * Setter for <code>Java.Sessions.session_id</code>.
     */
    public void setSessionId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Java.Sessions.session_id</code>.
     */
    public Integer getSessionId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Java.Sessions.cookie</code>.
     */
    public void setCookie(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Java.Sessions.cookie</code>.
     */
    public String getCookie() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Java.Sessions.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>Java.Sessions.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Sessions.SESSIONS.SESSION_ID;
    }

    @Override
    public Field<String> field2() {
        return Sessions.SESSIONS.COOKIE;
    }

    @Override
    public Field<Integer> field3() {
        return Sessions.SESSIONS.USER_ID;
    }

    @Override
    public Integer component1() {
        return getSessionId();
    }

    @Override
    public String component2() {
        return getCookie();
    }

    @Override
    public Integer component3() {
        return getUserId();
    }

    @Override
    public Integer value1() {
        return getSessionId();
    }

    @Override
    public String value2() {
        return getCookie();
    }

    @Override
    public Integer value3() {
        return getUserId();
    }

    @Override
    public SessionsRecord value1(Integer value) {
        setSessionId(value);
        return this;
    }

    @Override
    public SessionsRecord value2(String value) {
        setCookie(value);
        return this;
    }

    @Override
    public SessionsRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public SessionsRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SessionsRecord
     */
    public SessionsRecord() {
        super(Sessions.SESSIONS);
    }

    /**
     * Create a detached, initialised SessionsRecord
     */
    public SessionsRecord(Integer sessionId, String cookie, Integer userId) {
        super(Sessions.SESSIONS);

        set(0, sessionId);
        set(1, cookie);
        set(2, userId);
    }
}
