/*
 * This file is generated by jOOQ.
 */
package com.astroapi.db.routines;


import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;

import com.astroapi.db.Java;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddNewUser extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -609443262;

    /**
     * The parameter <code>Java.Add_New_User.inEmail</code>.
     */
    public static final Parameter<String> INEMAIL = Internal.createParameter("inEmail", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * The parameter <code>Java.Add_New_User.inPass</code>.
     */
    public static final Parameter<String> INPASS = Internal.createParameter("inPass", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * The parameter <code>Java.Add_New_User.inUserName</code>.
     */
    public static final Parameter<String> INUSERNAME = Internal.createParameter("inUserName", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * Create a new routine call instance
     */
    public AddNewUser() {
        super("Add_New_User", Java.JAVA);

        addInParameter(INEMAIL);
        addInParameter(INPASS);
        addInParameter(INUSERNAME);
    }

    /**
     * Set the <code>inEmail</code> parameter IN value to the routine
     */
    public void setInemail(String value) {
        setValue(INEMAIL, value);
    }

    /**
     * Set the <code>inPass</code> parameter IN value to the routine
     */
    public void setInpass(String value) {
        setValue(INPASS, value);
    }

    /**
     * Set the <code>inUserName</code> parameter IN value to the routine
     */
    public void setInusername(String value) {
        setValue(INUSERNAME, value);
    }
}
