/*
 * This file is generated by jOOQ.
 */
package com.astroapi.db.routines;


import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;

import com.astroapi.db.Java;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CreateVerification extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1645263213;

    /**
     * The parameter <code>Java.Create_Verification.inEmail</code>.
     */
    public static final Parameter<String> INEMAIL = Internal.createParameter("inEmail", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * The parameter <code>Java.Create_Verification.inTime</code>.
     */
    public static final Parameter<String> INTIME = Internal.createParameter("inTime", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * The parameter <code>Java.Create_Verification.inCode</code>.
     */
    public static final Parameter<String> INCODE = Internal.createParameter("inCode", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * Create a new routine call instance
     */
    public CreateVerification() {
        super("Create_Verification", Java.JAVA);

        addInParameter(INEMAIL);
        addInParameter(INTIME);
        addInParameter(INCODE);
    }

    /**
     * Set the <code>inEmail</code> parameter IN value to the routine
     */
    public void setInemail(String value) {
        setValue(INEMAIL, value);
    }

    /**
     * Set the <code>inTime</code> parameter IN value to the routine
     */
    public void setIntime(String value) {
        setValue(INTIME, value);
    }

    /**
     * Set the <code>inCode</code> parameter IN value to the routine
     */
    public void setIncode(String value) {
        setValue(INCODE, value);
    }
}
