/*
 * This file is generated by jOOQ.
 */
package com.astroapi.db.routines;


import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;

import com.astroapi.db.Java;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeleteUserById extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 520310680;

    /**
     * The parameter <code>Java.Delete_User_By_Id.userId</code>.
     */
    public static final Parameter<Integer> USERID = Internal.createParameter("userId", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public DeleteUserById() {
        super("Delete_User_By_Id", Java.JAVA);

        addInParameter(USERID);
    }

    /**
     * Set the <code>userId</code> parameter IN value to the routine
     */
    public void setUserid(Integer value) {
        setValue(USERID, value);
    }
}
