/*
 * This file is generated by jOOQ.
 */
package com.astroapi.db.routines;


import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;

import com.astroapi.db.Java;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeleteSessionByCookie extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 104826582;

    /**
     * The parameter <code>Java.Delete_Session_By_Cookie.cook</code>.
     */
    public static final Parameter<String> COOK = Internal.createParameter("cook", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * Create a new routine call instance
     */
    public DeleteSessionByCookie() {
        super("Delete_Session_By_Cookie", Java.JAVA);

        addInParameter(COOK);
    }

    /**
     * Set the <code>cook</code> parameter IN value to the routine
     */
    public void setCook(String value) {
        setValue(COOK, value);
    }
}
