/*
 * This file is generated by jOOQ.
 */
package com.astroapi.db.routines;


import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;

import com.astroapi.db.Java;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetUserSession extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -1102333197;

    /**
     * The parameter <code>Java.Get_User_Session.input</code>.
     */
    public static final Parameter<String> INPUT = Internal.createParameter("input", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * The parameter <code>Java.Get_User_Session.cook</code>.
     */
    public static final Parameter<String> COOK = Internal.createParameter("cook", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * The parameter <code>Java.Get_User_Session.id</code>.
     */
    public static final Parameter<Integer> ID = Internal.createParameter("id", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>Java.Get_User_Session.lname</code>.
     */
    public static final Parameter<String> LNAME = Internal.createParameter("lname", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * The parameter <code>Java.Get_User_Session.fname</code>.
     */
    public static final Parameter<String> FNAME = Internal.createParameter("fname", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * The parameter <code>Java.Get_User_Session.email</code>.
     */
    public static final Parameter<String> EMAIL = Internal.createParameter("email", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * The parameter <code>Java.Get_User_Session.age</code>.
     */
    public static final Parameter<Integer> AGE = Internal.createParameter("age", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>Java.Get_User_Session.verified</code>.
     */
    public static final Parameter<Byte> VERIFIED = Internal.createParameter("verified", org.jooq.impl.SQLDataType.TINYINT, false, false);

    /**
     * The parameter <code>Java.Get_User_Session.userName</code>.
     */
    public static final Parameter<String> USERNAME = Internal.createParameter("userName", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * Create a new routine call instance
     */
    public GetUserSession() {
        super("Get_User_Session", Java.JAVA);

        addInParameter(INPUT);
        addOutParameter(COOK);
        addOutParameter(ID);
        addOutParameter(LNAME);
        addOutParameter(FNAME);
        addOutParameter(EMAIL);
        addOutParameter(AGE);
        addOutParameter(VERIFIED);
        addOutParameter(USERNAME);
    }

    /**
     * Set the <code>input</code> parameter IN value to the routine
     */
    public void setInput(String value) {
        setValue(INPUT, value);
    }

    /**
     * Get the <code>cook</code> parameter OUT value from the routine
     */
    public String getCook() {
        return get(COOK);
    }

    /**
     * Get the <code>id</code> parameter OUT value from the routine
     */
    public Integer getId() {
        return get(ID);
    }

    /**
     * Get the <code>lname</code> parameter OUT value from the routine
     */
    public String getLname() {
        return get(LNAME);
    }

    /**
     * Get the <code>fname</code> parameter OUT value from the routine
     */
    public String getFname() {
        return get(FNAME);
    }

    /**
     * Get the <code>email</code> parameter OUT value from the routine
     */
    public String getEmail() {
        return get(EMAIL);
    }

    /**
     * Get the <code>age</code> parameter OUT value from the routine
     */
    public Integer getAge() {
        return get(AGE);
    }

    /**
     * Get the <code>verified</code> parameter OUT value from the routine
     */
    public Byte getVerified() {
        return get(VERIFIED);
    }

    /**
     * Get the <code>userName</code> parameter OUT value from the routine
     */
    public String getUsername() {
        return get(USERNAME);
    }
}
