/*
 * This file is generated by jOOQ.
 */
package com.astroapi.db.routines;


import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;

import com.astroapi.db.Java;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetUserByEmail extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -729630383;

    /**
     * The parameter <code>Java.Get_User_By_Email.inEmail</code>.
     */
    public static final Parameter<String> INEMAIL = Internal.createParameter("inEmail", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * The parameter <code>Java.Get_User_By_Email.userId</code>.
     */
    public static final Parameter<Integer> USERID = Internal.createParameter("userId", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>Java.Get_User_By_Email.userLastName</code>.
     */
    public static final Parameter<String> USERLASTNAME = Internal.createParameter("userLastName", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * The parameter <code>Java.Get_User_By_Email.userFirstName</code>.
     */
    public static final Parameter<String> USERFIRSTNAME = Internal.createParameter("userFirstName", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * The parameter <code>Java.Get_User_By_Email.userEmail</code>.
     */
    public static final Parameter<String> USEREMAIL = Internal.createParameter("userEmail", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * The parameter <code>Java.Get_User_By_Email.userAge</code>.
     */
    public static final Parameter<Integer> USERAGE = Internal.createParameter("userAge", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>Java.Get_User_By_Email.userVerified</code>.
     */
    public static final Parameter<Byte> USERVERIFIED = Internal.createParameter("userVerified", org.jooq.impl.SQLDataType.TINYINT, false, false);

    /**
     * The parameter <code>Java.Get_User_By_Email.userName</code>.
     */
    public static final Parameter<String> USERNAME = Internal.createParameter("userName", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * Create a new routine call instance
     */
    public GetUserByEmail() {
        super("Get_User_By_Email", Java.JAVA);

        addInParameter(INEMAIL);
        addOutParameter(USERID);
        addOutParameter(USERLASTNAME);
        addOutParameter(USERFIRSTNAME);
        addOutParameter(USEREMAIL);
        addOutParameter(USERAGE);
        addOutParameter(USERVERIFIED);
        addOutParameter(USERNAME);
    }

    /**
     * Set the <code>inEmail</code> parameter IN value to the routine
     */
    public void setInemail(String value) {
        setValue(INEMAIL, value);
    }

    /**
     * Get the <code>userId</code> parameter OUT value from the routine
     */
    public Integer getUserid() {
        return get(USERID);
    }

    /**
     * Get the <code>userLastName</code> parameter OUT value from the routine
     */
    public String getUserlastname() {
        return get(USERLASTNAME);
    }

    /**
     * Get the <code>userFirstName</code> parameter OUT value from the routine
     */
    public String getUserfirstname() {
        return get(USERFIRSTNAME);
    }

    /**
     * Get the <code>userEmail</code> parameter OUT value from the routine
     */
    public String getUseremail() {
        return get(USEREMAIL);
    }

    /**
     * Get the <code>userAge</code> parameter OUT value from the routine
     */
    public Integer getUserage() {
        return get(USERAGE);
    }

    /**
     * Get the <code>userVerified</code> parameter OUT value from the routine
     */
    public Byte getUserverified() {
        return get(USERVERIFIED);
    }

    /**
     * Get the <code>userName</code> parameter OUT value from the routine
     */
    public String getUsername() {
        return get(USERNAME);
    }
}
