/*
 * This file is generated by jOOQ.
 */
package com.astroapi.db.routines;


import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;

import com.astroapi.db.Java;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetVerification extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -979093908;

    /**
     * The parameter <code>Java.Get_Verification.inEmail</code>.
     */
    public static final Parameter<String> INEMAIL = Internal.createParameter("inEmail", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * The parameter <code>Java.Get_Verification.email</code>.
     */
    public static final Parameter<String> EMAIL = Internal.createParameter("email", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * The parameter <code>Java.Get_Verification.expiry</code>.
     */
    public static final Parameter<String> EXPIRY = Internal.createParameter("expiry", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * The parameter <code>Java.Get_Verification.verificationCode</code>.
     */
    public static final Parameter<String> VERIFICATIONCODE = Internal.createParameter("verificationCode", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * Create a new routine call instance
     */
    public GetVerification() {
        super("Get_Verification", Java.JAVA);

        addInParameter(INEMAIL);
        addOutParameter(EMAIL);
        addOutParameter(EXPIRY);
        addOutParameter(VERIFICATIONCODE);
    }

    /**
     * Set the <code>inEmail</code> parameter IN value to the routine
     */
    public void setInemail(String value) {
        setValue(INEMAIL, value);
    }

    /**
     * Get the <code>email</code> parameter OUT value from the routine
     */
    public String getEmail() {
        return get(EMAIL);
    }

    /**
     * Get the <code>expiry</code> parameter OUT value from the routine
     */
    public String getExpiry() {
        return get(EXPIRY);
    }

    /**
     * Get the <code>verificationCode</code> parameter OUT value from the routine
     */
    public String getVerificationcode() {
        return get(VERIFICATIONCODE);
    }
}
