/*
 * This file is generated by jOOQ.
 */
package com.astroapi.db.routines;


import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;

import com.astroapi.db.Java;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreSession extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -510511186;

    /**
     * The parameter <code>Java.Store_Session.cook</code>.
     */
    public static final Parameter<String> COOK = Internal.createParameter("cook", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * The parameter <code>Java.Store_Session.uid</code>.
     */
    public static final Parameter<Integer> UID = Internal.createParameter("uid", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public StoreSession() {
        super("Store_Session", Java.JAVA);

        addInParameter(COOK);
        addInParameter(UID);
    }

    /**
     * Set the <code>cook</code> parameter IN value to the routine
     */
    public void setCook(String value) {
        setValue(COOK, value);
    }

    /**
     * Set the <code>uid</code> parameter IN value to the routine
     */
    public void setUid(Integer value) {
        setValue(UID, value);
    }
}
